---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student-mgmt
    username: synerzip
    password: synerzip123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name: student-service
server:
  port: 3000
synerzip:
  bu: Bu-9